# Documentation available at https://expeditor.chef.io/

project:
  alias: "habitat"

github:
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  # TODO: Change this to `VERSION` once we are live
  version_file: "VERSION_FAKE"
  version_tag_format: 'fake-{{version}}'
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG_FAKE.md"
  delete_branch_on_merge: true

# Slack channel in Chef Software slack to send notifications about Expeditor actions
slack:
  notify_channel: habitat-notify

changelog:
  categories:
    - "X-change": "Behavioral Changes"
    - "X-feature": "New Features & Enhancements"
    - "X-fix": "Bug Fixes"
  rollup_header: Changes not yet released to stable

pipelines:
  - verify:
      description: Pull Request validation tests
  - website:
      description: Deploy the website
      trigger: pull_request
  - release_habitat:
      description: Habitat release process
  - end_to_end:
      description: Habitat long running end to end tests - always runs on DEV environment
  - finish_release:
      description: Tasks to be performed after a release has been promoted to stable

staging_areas:
  - release_staging:
      workload: pull_request_merged:{{agent_id}}:*

subscriptions:
  - workload: pull_request_opened:{{agent_id}}:*
    actions:
      - post_github_comment:.expeditor/templates/welcome.mustache:
          ignore_team_members:
            - habitat-sh/habitat-core-maintainers
      - built_in:github_auto_assign_author:
          only_if_team_member:
            - habitat-sh/habitat-core-maintainers


  - workload: staged_workload_released:{{agent_id}}:release_staging:*
    actions:
      - built_in:bump_version
      - built_in:update_changelog
      - trigger_pipeline:release_habitat:
          only_if: built_in:bump_version

  # Responses to Release Pipeline
  ########################################################################

  - workload: buildkite_build_passed:{{agent_id}}:release_habitat:*
    actions:
      - trigger_pipeline:end_to_end
      - unlock_staging_area:release_staging:
          always_run: true
      - bash:.expeditor/scripts/release_habitat/expeditor_destroy_build_channel.sh:
          always_run: true
          post_commit: true

  # Make sure we unlock to allow later builds if one fails.
  - workload: buildkite_build_failed:{{agent_id}}:release_habitat:*
    actions:
      - unlock_staging_area:release_staging:
          always_run: true
      - bash:.expeditor/scripts/release_habitat/expeditor_destroy_build_channel.sh:
          always_run: true
          post_commit: true

  - workload: buildkite_build_canceled:{{agent_id}}:release_habitat:*
    actions:
      - unlock_staging_area:release_staging:
          always_run: true
      - bash:.expeditor/scripts/release_habitat/expeditor_destroy_build_channel.sh:
          always_run: true
          post_commit: true

  # Responses to End-To-End Pipeline
  ########################################################################

  - workload: buildkite_build_passed:{{agent_id}}:end_to_end:*
    actions:
      - trigger_pipeline:test_scenarios

  # Scheduled Pipelines
  ########################################################################

  - workload: schedule_triggered:{{agent_id}}:cargo_update:*
    actions:
      - bash:.expeditor/scripts/cargo_update.sh

  # Promotion Workloads
  ########################################################################
  # Only allow promotion actions from acceptance (to current) and
  # current (to stable); other promotions are handled automatically by
  # the pipeline.
  - workload: project_promoted:{{agent_id}}:acceptance:*
    actions:
      - bash:.expeditor/scripts/expeditor_promote.sh
      - bash:.expeditor/scripts/purge-cdn.sh:
          post_commit: true

  - workload: project_promoted:{{agent_id}}:current:*
    actions:
      - bash:.expeditor/scripts/expeditor_promote.sh
      - bash:.expeditor/scripts/purge-cdn.sh:
          post_commit: true

schedules:
  - name: cargo_update
    description: "Run 'cargo update' every Monday at 12PM UTC"
    cronline: "0 12 * * 1"

promote:
  channels:
    # e2e pipeline tests from here
    - dev
    # acceptance Builder Supervisors update from here
    - acceptance
    # prod Builder Supervisors update from here
    - current
    # Habitat packages in stable, binary packages available to the world
    - stable
